export default class SettingsOptions{
    
    static data = [{
        id: 1,
        title: "Data path",
        subTitle: "/data",
        dialogTitle: "Data Path",
        dialogMessage: "Set the new path to find the data generated by the algorithms."
    }, {
        id: 2,
        title: "File dilemeter",
        subTitle: ";",
        dialogTitle: "File dilemeter",
        dialogMessage: "Set the new dilementer in the files to extract the data from it."
    }, {
        id: 3,
        title: "File pattern",
        subTitle: "*_data.csv",
        dialogTitle: "File pattern",
        dialogMessage: "Choose the file pattern of the files that contain the data."
    }];

}